/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestDriveRouteImport } from './routes/test-drive'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarroSlugRouteImport } from './routes/carro.$slug'

const TestDriveRoute = TestDriveRouteImport.update({
  id: '/test-drive',
  path: '/test-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarroSlugRoute = CarroSlugRouteImport.update({
  id: '/carro/$slug',
  path: '/carro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/localizacao': typeof LocalizacaoRoute
  '/noticias': typeof NoticiasRoute
  '/sobre': typeof SobreRoute
  '/test-drive': typeof TestDriveRoute
  '/carro/$slug': typeof CarroSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/localizacao': typeof LocalizacaoRoute
  '/noticias': typeof NoticiasRoute
  '/sobre': typeof SobreRoute
  '/test-drive': typeof TestDriveRoute
  '/carro/$slug': typeof CarroSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/localizacao': typeof LocalizacaoRoute
  '/noticias': typeof NoticiasRoute
  '/sobre': typeof SobreRoute
  '/test-drive': typeof TestDriveRoute
  '/carro/$slug': typeof CarroSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/localizacao'
    | '/noticias'
    | '/sobre'
    | '/test-drive'
    | '/carro/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/localizacao'
    | '/noticias'
    | '/sobre'
    | '/test-drive'
    | '/carro/$slug'
  id:
    | '__root__'
    | '/'
    | '/localizacao'
    | '/noticias'
    | '/sobre'
    | '/test-drive'
    | '/carro/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocalizacaoRoute: typeof LocalizacaoRoute
  NoticiasRoute: typeof NoticiasRoute
  SobreRoute: typeof SobreRoute
  TestDriveRoute: typeof TestDriveRoute
  CarroSlugRoute: typeof CarroSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-drive': {
      id: '/test-drive'
      path: '/test-drive'
      fullPath: '/test-drive'
      preLoaderRoute: typeof TestDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carro/$slug': {
      id: '/carro/$slug'
      path: '/carro/$slug'
      fullPath: '/carro/$slug'
      preLoaderRoute: typeof CarroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocalizacaoRoute: LocalizacaoRoute,
  NoticiasRoute: NoticiasRoute,
  SobreRoute: SobreRoute,
  TestDriveRoute: TestDriveRoute,
  CarroSlugRoute: CarroSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
